# 该工作流将使用单个版本的Python安装Python依赖项、运行测试和代码检查
# 更多信息请参见：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

名称：Python 应用程序: Python application

在::
  推送::
    分支: [ "master" ]: [ "master" ]
  拉取请求::
    分支: [ "master" ]: [ "master" ]

权限：:
  内容：阅读: read

工作::
  构建::

    运行于: ubuntu-latest: ubuntu-latest

    步骤：:
    - 使用：actions/checkout@v4uses: actions/checkout@v4
    - name: 设置 Python 3.10name: Set up Python 3.10
      用途: actions/setup-python@v3: actions/setup-python@v3
      与：:
        python-version: "3.10": "3.10"
    - 名称: 安装依赖项name: Install dependencies
      运行：|: |
        python -m pip install --upgrade pip
        使用pip安装flake8和pytest：  
```bash
pip install flake8 pytest
```
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - 名称: Lint with flake8name: Lint with flake8
      运行：|: |
        # 如果有Python语法错误或未定义的名称，请停止构建
        flake8 . --count --select=E9,F63,F7,F82 --show-source --统计数据
        # exit-zero 将所有错误视为警告。GitHub 编辑器宽 127 字符
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
